/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ntou.cs.java.TimeMachine;
import java.math.BigDecimal;
/**
 *
 * @author 桌電
 */


public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form SwingCalculator
     */
    public Calculator() {
        initComponents();
    }

    private boolean number = true;
    private String equalOp = "=";
    private Calculator.CalculatorOp calculatorOp = new Calculator.CalculatorOp();
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtField.setText("0");
        txtField.setCursor(new java.awt.Cursor(java.awt.Cursor.NE_RESIZE_CURSOR));

        jPanel2.setToolTipText("");
        jPanel2.setLayout(new java.awt.GridLayout(4, 3, 2, 2));

        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton5.setText("3");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton9.setText("4");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton7.setText("5");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setText("6");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton13.setText("7");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton13);

        jButton11.setText("8");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton12.setText("9");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton17.setText("C");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorListener(evt);
            }
        });
        jPanel2.add(jButton17);

        jButton15.setText("0");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton15);

        jButton16.setText(".");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberListener(evt);
            }
        });
        jPanel2.add(jButton16);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 4, 2));

        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorListener(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton10.setText("*");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorListener(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton14.setText("/");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorListener(evt);
            }
        });
        jPanel3.add(jButton14);

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorListener(evt);
            }
        });
        jPanel3.add(jButton4);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButton18.setText("=");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorListener(evt);
            }
        });
        jPanel4.add(jButton18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberListener
       String digit = evt.getActionCommand();
       if (number) {
         txtField.setText(digit);
   	 number = false;
      } else {
    	txtField.setText(txtField.getText() + digit);
      }
    }//GEN-LAST:event_NumberListener

    private void OperatorListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperatorListener
    if (number&&(!"=".equals(equalOp))) {
            action();
            txtField.setText("0");
      } else {
    	number = true;
   	 String displayText = txtField.getText();
   	 switch(equalOp) {
   	   case "=":
   	 	calculatorOp.setTotal(displayText);
   	   break;
   	   case "+":
   	 	calculatorOp.add(displayText);
   	   break;
   	   case "-":
   	 	calculatorOp.subtract(displayText);
           break;
   	   case "*":
   	 	calculatorOp.multiply(displayText);
   	   break;
   	   case "/":
   	 	calculatorOp.divide(displayText);
   	   break;
   	 }
   	 if("C".equals(evt.getActionCommand()))
             action();
         else{
             txtField.setText("" + calculatorOp.getTotalString());
             equalOp = evt.getActionCommand();
         }

      }
    }//GEN-LAST:event_OperatorListener

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
  private void action() {
    number = true;
    txtField.setText("0");
    equalOp = "=";
    calculatorOp.setTotal("0");
  }

    class CalculatorOp {
      private double total;
      public CalculatorOp() {
   	 total = 0;
      }
      
      public String getTotalString() {
          if(total%1==0){
             return String.valueOf((int)total);
          }
   	 return String.valueOf(total);
      }
      
      public void setTotal(String value) {
   	 total = Double.parseDouble(value);
      }
      
      public void add(String value) {
         BigDecimal b1 = new BigDecimal(Double.toString(total));
         BigDecimal b2 = new BigDecimal(value);
         total = b1.add(b2).doubleValue();
      }
      
      public void subtract(String value) {
          BigDecimal b1 = new BigDecimal(Double.toString(total));
         BigDecimal b2 = new BigDecimal(value);
         total = b1.subtract(b2).doubleValue();
      }
      
      public void multiply(String value) {
          BigDecimal b1 = new BigDecimal(Double.toString(total));
         BigDecimal b2 = new BigDecimal(value);
         total = b1.multiply(b2).doubleValue();
      }
      
      public void divide(String value) {
   	  try{
              BigDecimal b1 = new BigDecimal(Double.toString(total));
              BigDecimal b2 = new BigDecimal(value);
              total = b1.divide(b2).doubleValue();
          }
          catch (Exception  e) {
              action();
              txtField.setText("ERROR");
        }
      }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
